#!/usr/bin/env node
// explore_catalog_index.js — turn an explore-catalog dump into (a) the generated field index in the
// dutchie-bi-looker skill references (tracked; the model is Dutchie's shared reporting model, no tenant
// data) and (b) a diff against the previous dump. Zero dependencies.
//   node <skill>/scripts/explore_catalog_index.js <estate>/explore-catalog-<date>.json [--index <out.md>]
const fs = require('fs'); const path = require('path');
const args = process.argv.slice(2); const src = args.find(a => !a.startsWith('--'));
if (!src) { console.log('usage: explore_catalog_index.js <explore-catalog-<date>.json> [--index <out.md>]'); process.exit(1); }
const EST = path.dirname(path.resolve(src));
// Repo root is FOUND, not counted in `..`s (P6, 2026-09-08). This file moved from
// a client scripts dir (3 levels down) into the bi-change skill (4 levels down); a hardcoded
// depth silently writes the index to the wrong place rather than failing, so walk up to the
// directory that actually holds freed-solutions/skills.
function findRepo(start) {
  let d = start;
  for (let i = 0; i < 10; i++) {
    if (fs.existsSync(path.join(d, 'freed-solutions', 'skills'))) return d;
    const up = path.dirname(d);
    if (up === d) break;
    d = up;
  }
  throw new Error('explore_catalog_index: cannot locate the repo root above ' + start +
    ' (looked for freed-solutions/skills). Pass --index <out.md> explicitly.');
}
const REPO = args.includes('--index') ? null : findRepo(__dirname);
const OUT = args.includes('--index') ? args[args.indexOf('--index') + 1] : path.join(REPO, 'freed-solutions', 'skills', 'dutchie-bi-looker', 'references', 'explore-field-index.md');

function load(p) { let t = fs.readFileSync(p, 'utf8'); let d = JSON.parse(t); if (typeof d === 'string') d = JSON.parse(d); return d; }
const cur = load(src);
const prevFile = fs.readdirSync(EST).filter(f => /^explore-catalog-\d{4}-\d{2}-\d{2}.*\.json$/.test(f) && path.resolve(EST, f) !== path.resolve(src)).sort().pop();
const prev = prevFile ? load(path.join(EST, prevFile)) : null;

const key = (e, f) => e.name + ' ' + f.name;
const fieldSet = (d) => { const s = new Map(); for (const e of d.explores) for (const f of [...e.dimensions, ...e.measures]) s.set(key(e, f), f); return s; };
// two counts, both true: ENTRIES (a field counted once per explore it is reachable on) and DISTINCT NAMES
const total = (d) => d.explores.reduce((n, e) => n + e.dimensions.length + e.measures.length, 0);
const distinct = (d) => new Set(d.explores.flatMap(e => [...e.dimensions, ...e.measures].map(f => f.name))).size;

// ---------- diff ----------
console.log(`current: ${path.basename(src)} — ${cur.explore_count} explores, ${total(cur)} field entries (${distinct(cur)} distinct names) (harvested ${cur.harvested_at})`);
if (prev) {
  const a = fieldSet(prev), b = fieldSet(cur);
  const added = [...b.keys()].filter(k => !a.has(k)), removed = [...a.keys()].filter(k => !b.has(k));
  const ex = new Set(cur.explores.map(e => e.name)), exPrev = new Set(prev.explores.map(e => e.name));
  console.log(`previous: ${prevFile} — ${prev.explore_count} explores, ${total(prev)} fields`);
  console.log(`explores added: ${[...ex].filter(x => !exPrev.has(x)).join(', ') || 'none'} | removed: ${[...exPrev].filter(x => !ex.has(x)).join(', ') || 'none'}`);
  console.log(`fields added: ${added.length} | removed: ${removed.length}`);
  for (const k of added.slice(0, 40)) console.log('  + ' + k); for (const k of removed.slice(0, 40)) console.log('  - ' + k);
} else console.log('no previous dump — this is the baseline');

// ---------- index ----------
const L = [];
L.push('# Looker model `sql_server` — generated explore / view / field index');
L.push('');
L.push(`Generated by \`explore_catalog_index.js\` from an internal-API harvest on **${cur.harvested_at.slice(0, 10)}** (${cur.explore_count} explores, ${total(cur)} field entries — a field counted once per explore it is reachable on — ${distinct(cur)} distinct field names). Do not edit by hand — re-harvest under the \`bi-change\` \`sync\` path. The curated companion (mandatory filters, recipes, semantics) is \`explore-field-catalog.md\`; this file answers "does the field exist, on which explore, from which view, what type" and nothing else.`);
L.push('');
L.push('## Explores');
L.push(''); L.push('| Explore | Label | Views | Dimensions | Measures |'); L.push('|---|---|---|---|---|');
for (const e of cur.explores) L.push(`| \`${e.name}\` | ${e.label} | ${e.views.map(v => '`' + v + '`').join(' ')} | ${e.dimensions.length} | ${e.measures.length} |`);
L.push('');
L.push('## Fields by view (union across explores; the explores column says where each field is reachable)');
const byView = new Map();
for (const e of cur.explores) for (const [kind, arr] of [['dim', e.dimensions], ['meas', e.measures]]) for (const f of arr) {
  const v = f.view; if (!byView.has(v)) byView.set(v, new Map());
  const m = byView.get(v); const rec = m.get(f.name) || { f, kind, explores: new Set() }; rec.explores.add(e.name); m.set(f.name, rec);
}
for (const [v, m] of [...byView.entries()].sort()) {
  L.push(''); L.push(`### \`${v}\` (${m.size})`); L.push(''); L.push('| Field | Label | Kind | Type | Hidden | Explores |'); L.push('|---|---|---|---|---|---|');
  for (const [name, rec] of [...m.entries()].sort()) L.push(`| \`${name}\` | ${(rec.f.label || '').replace(/\|/g, '\\|')} | ${rec.kind} | ${rec.f.type} | ${rec.f.hidden ? 'yes' : ''} | ${[...rec.explores].sort().join(', ')} |`);
}
fs.writeFileSync(OUT, L.join('\n') + '\n');
console.log(`index written: ${OUT} (${L.length} lines, ${byView.size} views)`);
