// ===================================================
// Default Slide Factory
// ===================================================

function makeDefaultSlide(title, body) {
  return {
    title: title || "New Slide",
    showHeading: true,
    showAccentBar: true,
    body: body || "Your text here...",
    titleColor: "#ffffff",
    titleFontFamily: DEFAULT_FONT,
    titleBold: true,
    titleItalic: false,
    bodyColor: "#a5b4fc",
    bodyFontFamily: DEFAULT_FONT,
    bodyBold: false,
    bodyItalic: false,
    showCards: false,
    showCardChecks: true,
    cards: ["Card 1"],
    cardTextColor: "#333333",
    cardFontFamily: DEFAULT_FONT,
    cardBold: false,
    cardItalic: false,
    cardBgColor: "#ffffff",
    expandScreenshot: false,
    showScreenshot: false,
    showBrandName: false,
    brandNameText: "Brand Name",
    brandNameColor: "#1a1a2e",
    brandNameFontFamily: DEFAULT_FONT,
    brandNameBold: true,
    brandNameItalic: false,
    showTopCorner: false,
    topCornerText: "LABEL",
    topCornerColor: "#ffffff",
    topCornerFontFamily: DEFAULT_FONT,
    topCornerBold: true,
    topCornerItalic: false,
    topCornerOpacity: 40,
    showBottomCorner: false,
    bottomCornerText: "01 / ",
    bottomCornerColor: "#ffffff",
    bottomCornerFontFamily: DEFAULT_FONT,
    bottomCornerBold: false,
    bottomCornerItalic: false,
    bottomCornerOpacity: 35,
    solidColor: "#1e1e2e",
    bgType: "solid",
    customBgImage: null,
    customBgName: null,
    geoEnabled: true,
    geoLines: "#a0a0af",
    geoOpacity: 100,
    geoShape: "lines",
    frameEnabled: true,
    accentColor: "#a5b4fc",
    borderColor: "#ffffff",
    borderOpacity: 100,
    footerBg: "#ffffff",
    profileImg: null,
    profilePicName: null,
    headingSize: 48,
    bodySize: 38,
    cardTextSize: 22,
    topCornerSize: 13,
    bottomCornerSize: 16,
    brandNameSize: 20
  };
}